Namespace change
Vonage/vonage-python-code-snippets pull request #71
Opened 2020-09-10 14:22 UTC by superdiana

2020-09-10 18:20 UTC, slorello89 requested changes
Few items:
1. We have a somewhat inconsistent method of loading environment vars into the scripts. I think our best bet would be to have everything use dotenv - I've made notes where the dotenv's path was off, or the load was missing altogether.
2. I think there's some missing updates from the README - definitely many references to nexmo in there.
3. Some trivial comments requesting minor formatting changes.

2020-09-10 18:20 UTC, slorello89 commented on voice/join-outbound-calls.py
> +
Missing where the variables here come from - supposed to edit ahead of time? Maybe we could use dotenv? :)

2020-09-10 18:20 UTC, slorello89 commented on voice/make-outbound-call-ncco.py
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/play-audio-stream-into-call.py
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/play-dtmf-into-call.py
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/play-tts-into-call.py
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/record-a-call-with-split-audio.py
Missing where the variables are meant to be added here - I'm thinking have env variables would be preferable?

2020-09-10 18:20 UTC, slorello89 commented on voice/record-a-call-with-split-audio.py
> +            "text": "Hi, we will shortly forward your call. This call is recorded for quality assurance purposes.",
extra comma at the end here

2020-09-10 18:20 UTC, slorello89 commented on voice/record-a-call.py
> +
remove extra whitespace here and on line 25

2020-09-10 18:20 UTC, slorello89 commented on voice/retrieve-info-for-a-call.py
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/retrieve-info-for-all-calls.py
> +import vonage, os
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/transfer-a-call.py
missing dotenv load

2020-09-10 18:20 UTC, slorello89 commented on voice/transfer-call-inline-ncco.py
> +envpath = join(dirname(__file__), "./.env")
missing `.` in path

2020-09-10 18:20 UTC, slorello89 commented on application/delete-application.py
> +import vonage, os
missing dotnev load

2020-09-10 18:20 UTC, slorello89 commented on application/get-application.py
> +import vonage, os
missing dotnev load

2020-09-10 18:20 UTC, slorello89 commented on application/list-applications.py
> +import vonage, os
missing dotnev load

2020-09-10 18:20 UTC, slorello89 commented on application/update-application.py
>  from pprint import pprint
missing dotnev load

2020-09-10 18:20 UTC, slorello89 commented on initialize/application.py
missing dotnev load

2020-09-10 18:20 UTC, slorello89 commented on initialize/basic.py
missing dotnev load

2020-09-10 18:20 UTC, slorello89 commented on initialize/full.py
missing dotnev load

2020-09-10 20:25 UTC, slorello89 commented
also, requirements.txt needs to point at the vonage package.

2020-09-14 18:44 UTC, dragonmantank commented on application/create-application.py
That sound suspiciously like a good first issue for someone :smile: 

In general standalone scripts should pull from the root of the problem, full apps (like ones testing webhooks) should have their own .env files as those types of examples should be self-contained.

2020-09-17 12:54 UTC, slorello89 reviewed
I've run everything, everything looks good

2020-09-17 12:55 UTC, slorello89 approved these changes
LGTM

2020-09-17 13:08 UTC, merged